FROM debian:stretch
MAINTAINER Viktor Farcic "viktor@farcic.com"

ENV VERSION 1.0

RUN apt-get update

# CUrl (layer 5-7)
RUN apt install -y -f
RUN apt-get install -y -f curl
RUN echo 'deb http://ftp.au.debian.org/debian/ stretch main contrib non-free' > /etc/apt/sources.list.d/stretch.list && \
    apt-get update && \
    apt-get install -y openjdk-8-jdk openjdk-8-jre-headless

# Dependencies (layer 8-12)
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - 
RUN echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN curl -sL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN echo "deb http://packages.linuxmint.com debian import" >> /etc/apt/sources.list

# Mongo, NodeJS, Git, SBT, xvfb, FireFox, Chrome (layer 13-14)
RUN apt-get update && \
    apt-get -y --fix-missing install wget bzip2 make g++ && \
    apt-get -y --force-yes --fix-missing install --no-install-recommends mongodb git sbt=1.2.8 xvfb nodejs firefox google-chrome-stable && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-ca-certificates -f -v

# Scala (layer 15)
RUN curl -O -q http://downloads.typesafe.com/scala/2.12.0/scala-2.12.0.deb && \
    dpkg -i scala-2.12.0.deb && \
    rm scala-2.12.0.deb

# Gulp, bower (layer 16)
RUN npm install -g gulp bower

# Dirs (layer 17-26)
RUN mkdir /source
RUN mkdir -p /data/db

ADD project /source/project
ADD build.sbt /source/build.sbt
ADD client/bower.json /source/client/bower.json
ADD client/gulpfile.js /source/client/gulpfile.js
ADD client/package.json /source/client/package.json
ADD client/wct.conf.js /source/client/wct.conf.js
ADD client/test.html /source/client/test.html
ADD run_tests.sh /source/run_tests.sh

# Dependencies (layer 27-28)
RUN cd /source && sbt update
RUN cd /source/client && npm install && bower install --allow-root --config.interactive=false -s

# Envs (layer 29-36)
ENV TEST_TYPE "spec"
ENV DOMAIN "http://172.17.42.1"
ENV DISPLAY ":1.0"
ENV DB_HOST localhost

WORKDIR /source
VOLUME ["/source", "/source/target/scala-2.10", "/root/.ivy2/cache", "/data/db"]

CMD ["/source/run_tests.sh"]

EXPOSE 8080
